# Generated by Django 5.2.12 on 2026-03-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_rename_title_pokemon_title_ru_pokemon_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolution_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_to', to='pokemon_entities.pokemon'),
        ),
    ]
