# Generated by Django 5.2.12 on 2026-03-25 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemon_evolution_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolution_from',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolution_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_from', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал'),
        ),
    ]
