# Generated by Django 5.2.12 on 2026-03-25 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_remove_pokemon_evolution_to_pokemon_evolution_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolution_to', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал'),
        ),
    ]
